// src/components/workspace/ExploreGrid.vue
<template>
  <div class="mx-auto max-w-6xl">
    <div class="mb-6">
      <h2 class="text-2xl font-bold text-foreground">{{ t('workspace.exploreTitle') }}</h2>
      <p class="mt-1 text-sm text-muted-foreground">{{ t('workspace.exploreSubtitle') }}</p>
    </div>

    <div v-if="error" class="mb-4 rounded-lg bg-red-500/10 px-4 py-3 text-sm text-red-400">{{ error }}</div>

    <div class="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
      <button
        v-for="item in items"
        :key="item.id"
        class="group flex flex-col overflow-hidden rounded-xl border border-border bg-card text-left transition-all hover:border-primary/50 hover:shadow-lg"
        @click="$emit('open', item)"
      >
        <div class="aspect-[3/4] w-full overflow-hidden bg-secondary/40">
          <img
            v-if="cover(item)"
            :src="cover(item)"
            :alt="item.name || ''"
            loading="lazy"
            class="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
          />
          <div v-else class="flex h-full w-full items-center justify-center text-xs text-muted-foreground">{{ t('workspace.noCover') }}</div>
        </div>
        <div class="flex flex-1 flex-col p-3">
          <p class="line-clamp-2 text-sm font-medium text-foreground">{{ item.name || item.nameEn || t('workspace.unnamed') }}</p>
          <div class="mt-2 flex items-center gap-3 text-xs text-muted-foreground">
            <span v-if="item.authorNickname" class="truncate">{{ item.authorNickname }}</span>
            <span class="ml-auto flex items-center gap-1"><Eye class="h-3 w-3" />{{ item.viewCount ?? 0 }}</span>
            <span class="flex items-center gap-1"><Heart class="h-3 w-3" />{{ item.favoriteCount ?? 0 }}</span>
          </div>
        </div>
      </button>
    </div>

    <div v-if="loading" class="flex items-center justify-center py-8 text-muted-foreground">
      <Loader2 class="h-5 w-5 animate-spin" />
    </div>
    <div v-else-if="hasMore" class="mt-6 flex justify-center">
      <button
        class="rounded-lg border border-border bg-secondary/50 px-6 py-2.5 text-sm font-medium text-foreground transition-colors hover:border-primary/50"
        @click="load(page + 1)"
      >
        {{ t('workspace.loadMore') }}
      </button>
    </div>
    <p v-if="!loading && !items.length && !error" class="py-12 text-center text-sm text-muted-foreground">{{ t('workspace.noWorks') }}</p>
  </div>
</template>

<script setup>
import { ref, computed, onMounted } from 'vue'
import { useI18n } from 'vue-i18n'
import { Loader2, Eye, Heart } from 'lucide-vue-next'
import { feedApi } from '../../api'

defineEmits(['open'])

const { t } = useI18n()

const PAGE_SIZE = 24
const items = ref([])
const page = ref(1)
const total = ref(0)
const loading = ref(false)
const error = ref(null)

const hasMore = computed(() => items.value.length < total.value)
const cover = (item) => item.imageUrl || item.imageUrls?.[0] || ''

const load = async (p) => {
  loading.value = true
  error.value = null
  try {
    const res = await feedApi.getFeedStream({ page: p, pageSize: PAGE_SIZE, sort: 1 })
    items.value = p === 1 ? res.data : [...items.value, ...res.data]
    total.value = res.total
    page.value = p
  } catch (e) {
    error.value = e?.message || t('common.loadFailed')
  } finally {
    loading.value = false
  }
}

onMounted(() => load(1))
</script>

// components/workspace/explore-grid.tsx
"use client"

// 探索 Explore：分页 Feed 网格，点开进入只读预览
// @author hc @date 2026-06-04

import { useEffect, useState } from "react"
import { Loader2, Eye, Heart } from "lucide-react"
import { feedApi } from "@/lib/api"
import type { FeedStreamItemDto } from "@/lib/api"

interface ExploreGridProps {
  onOpen: (item: FeedStreamItemDto) => void
}

const PAGE_SIZE = 24

export function ExploreGrid({ onOpen }: ExploreGridProps) {
  const [items, setItems] = useState<FeedStreamItemDto[]>([])
  const [page, setPage] = useState(1)
  const [total, setTotal] = useState(0)
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState<string | null>(null)

  const load = async (p: number) => {
    setLoading(true)
    setError(null)
    try {
      const res = await feedApi.getFeedStream({ page: p, pageSize: PAGE_SIZE, sort: 1 })
      setItems((prev) => (p === 1 ? res.data : [...prev, ...res.data]))
      setTotal(res.total)
      setPage(p)
    } catch (e) {
      setError((e as Error).message || "加载失败")
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    load(1)
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [])

  const hasMore = items.length < total

  return (
    <div className="mx-auto max-w-6xl">
      <div className="mb-6">
        <h2 className="text-2xl font-bold text-foreground">探索作品</h2>
        <p className="mt-1 text-sm text-muted-foreground">看看大家做的书籍分析，点开可基于它再生成一份</p>
      </div>

      {error && (
        <div className="mb-4 rounded-lg bg-destructive/10 px-4 py-3 text-sm text-destructive">{error}</div>
      )}

      <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 lg:grid-cols-4">
        {items.map((item) => {
          const cover = item.imageUrl || item.imageUrls?.[0] || ""
          return (
            <button
              key={item.id}
              onClick={() => onOpen(item)}
              className="group flex flex-col overflow-hidden rounded-xl border border-border bg-card text-left transition-all hover:border-primary/50 hover:shadow-lg hover:shadow-primary/5"
            >
              <div className="aspect-[3/4] w-full overflow-hidden bg-secondary/40">
                {cover ? (
                  // eslint-disable-next-line @next/next/no-img-element
                  <img
                    src={cover}
                    alt={item.name || ""}
                    loading="lazy"
                    className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
                  />
                ) : (
                  <div className="flex h-full w-full items-center justify-center text-xs text-muted-foreground">
                    无封面
                  </div>
                )}
              </div>
              <div className="flex flex-1 flex-col p-3">
                <p className="line-clamp-2 text-sm font-medium text-foreground">
                  {item.name || item.nameEn || "未命名"}
                </p>
                <div className="mt-2 flex items-center gap-3 text-xs text-muted-foreground">
                  {item.authorNickname && <span className="truncate">{item.authorNickname}</span>}
                  <span className="ml-auto flex items-center gap-1">
                    <Eye className="h-3 w-3" />
                    {item.viewCount ?? 0}
                  </span>
                  <span className="flex items-center gap-1">
                    <Heart className="h-3 w-3" />
                    {item.favoriteCount ?? 0}
                  </span>
                </div>
              </div>
            </button>
          )
        })}
      </div>

      {loading && (
        <div className="flex items-center justify-center py-8 text-muted-foreground">
          <Loader2 className="h-5 w-5 animate-spin" />
        </div>
      )}

      {!loading && hasMore && (
        <div className="mt-6 flex justify-center">
          <button
            onClick={() => load(page + 1)}
            className="rounded-lg border border-border bg-secondary/50 px-6 py-2.5 text-sm font-medium text-foreground transition-colors hover:border-primary/50"
          >
            加载更多
          </button>
        </div>
      )}

      {!loading && items.length === 0 && !error && (
        <p className="py-12 text-center text-sm text-muted-foreground">暂无作品</p>
      )}
    </div>
  )
}
