// components/workspace/workspace-sidebar.tsx
"use client"

// 工作区左侧侧边栏：新建 / Explore / 我的历史 / 用户区
// @author hc @date 2026-06-04

import { Presentation, Plus, Compass, LogOut, FileText, Loader2 } from "lucide-react"
import type { ProjectVo } from "@/lib/api"

export type WorkspaceView = "new" | "explore" | "project"

interface WorkspaceSidebarProps {
  view: WorkspaceView
  activeProjectId: string | null
  nickName: string
  myProjects: ProjectVo[]
  loadingProjects: boolean
  onNew: () => void
  onExplore: () => void
  onOpenProject: (id: string) => void
  onLogout: () => void
}

export function WorkspaceSidebar({
  view,
  activeProjectId,
  nickName,
  myProjects,
  loadingProjects,
  onNew,
  onExplore,
  onOpenProject,
  onLogout,
}: WorkspaceSidebarProps) {
  return (
    <aside className="flex h-full w-64 flex-shrink-0 flex-col border-r border-border bg-sidebar">
      {/* 品牌 */}
      <div className="flex h-16 items-center gap-2 border-b border-border px-4">
        <div className="flex h-9 w-9 items-center justify-center rounded-lg bg-primary">
          <Presentation className="h-5 w-5 text-primary-foreground" />
        </div>
        <span className="text-lg font-bold text-foreground">SlideAI</span>
      </div>

      {/* 主操作 */}
      <div className="space-y-1 p-3">
        <button
          onClick={onNew}
          className={`flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${
            view === "new"
              ? "bg-primary text-primary-foreground"
              : "text-muted-foreground hover:bg-secondary hover:text-foreground"
          }`}
        >
          <Plus className="h-4 w-4" />
          新建生成
        </button>
        <button
          onClick={onExplore}
          className={`flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors ${
            view === "explore"
              ? "bg-primary text-primary-foreground"
              : "text-muted-foreground hover:bg-secondary hover:text-foreground"
          }`}
        >
          <Compass className="h-4 w-4" />
          探索 Explore
        </button>
      </div>

      {/* 我的历史 */}
      <div className="flex min-h-0 flex-1 flex-col px-3">
        <p className="px-2 py-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">
          我的历史
        </p>
        <div className="min-h-0 flex-1 space-y-0.5 overflow-y-auto">
          {loadingProjects ? (
            <div className="flex items-center gap-2 px-2 py-2 text-sm text-muted-foreground">
              <Loader2 className="h-4 w-4 animate-spin" />
              加载中...
            </div>
          ) : myProjects.length === 0 ? (
            <p className="px-2 py-2 text-xs text-muted-foreground/70">暂无记录</p>
          ) : (
            myProjects.map((p) => (
              <button
                key={p.id}
                onClick={() => onOpenProject(p.id)}
                title={p.name || p.title || p.id}
                className={`flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm transition-colors ${
                  view === "project" && activeProjectId === p.id
                    ? "bg-secondary text-foreground"
                    : "text-muted-foreground hover:bg-secondary/60 hover:text-foreground"
                }`}
              >
                <FileText className="h-4 w-4 flex-shrink-0" />
                <span className="truncate">{p.name || p.title || "未命名项目"}</span>
              </button>
            ))
          )}
        </div>
      </div>

      {/* 用户区 */}
      <div className="border-t border-border p-3">
        <div className="flex items-center justify-between gap-2">
          <span className="truncate text-sm text-muted-foreground">{nickName || "已登录"}</span>
          <button
            onClick={onLogout}
            title="退出登录"
            className="flex flex-shrink-0 items-center gap-1 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
          >
            <LogOut className="h-4 w-4" />
          </button>
        </div>
      </div>
    </aside>
  )
}

// src/components/workspace/WorkspaceSidebar.vue
<template>
  <aside class="flex h-full w-64 flex-shrink-0 flex-col border-r border-border bg-card">
    <div class="flex h-16 items-center gap-2 border-b border-border px-4">
      <div class="flex h-9 w-9 items-center justify-center rounded-lg bg-primary">
        <Presentation class="h-5 w-5 text-primary-foreground" />
      </div>
      <span class="text-lg font-bold text-foreground">{{ t('app.brand') }}</span>
    </div>

    <div class="space-y-1 p-3">
      <button :class="btnClass(view === 'new')" @click="$emit('new')">
        <Plus class="h-4 w-4" /> {{ t('workspace.newGenerate') }}
      </button>
      <button :class="btnClass(view === 'explore')" @click="$emit('explore')">
        <Compass class="h-4 w-4" /> {{ t('workspace.explore') }}
      </button>
    </div>

    <div class="flex min-h-0 flex-1 flex-col px-3">
      <p class="px-2 py-2 text-xs font-medium uppercase tracking-wider text-muted-foreground">{{ t('workspace.myHistory') }}</p>
      <div class="min-h-0 flex-1 space-y-0.5 overflow-y-auto">
        <div v-if="loadingProjects" class="flex items-center gap-2 px-2 py-2 text-sm text-muted-foreground">
          <Loader2 class="h-4 w-4 animate-spin" /> {{ t('workspace.loading') }}
        </div>
        <p v-else-if="!myProjects.length" class="px-2 py-2 text-xs text-muted-foreground/70">{{ t('workspace.noHistory') }}</p>
        <button
          v-for="p in myProjects"
          v-else
          :key="p.id"
          :title="p.name || p.title || p.id"
          :class="[
            'flex w-full items-center gap-2 rounded-lg px-2 py-2 text-left text-sm transition-colors',
            activeProjectId === p.id
              ? 'bg-secondary text-foreground'
              : 'text-muted-foreground hover:bg-secondary/60 hover:text-foreground',
          ]"
          @click="$emit('open-project', p.id)"
        >
          <img
            v-if="p.thumbnailUrl"
            :src="p.thumbnailUrl"
            alt=""
            class="h-8 w-8 flex-shrink-0 rounded object-cover"
            loading="lazy"
          />
          <FileText v-else class="h-4 w-4 flex-shrink-0" />
          <span class="truncate">{{ p.name || p.title || t('workspace.unnamedProject') }}</span>
        </button>
      </div>
    </div>

    <div class="border-t border-border p-3 space-y-3">
      <WorkspaceCreditsBar />
      <LocaleSwitcher />
      <div class="flex items-center justify-between gap-2">
        <div class="flex min-w-0 items-center gap-2">
          <img
            v-if="avatar"
            :src="avatar"
            :alt="nickName || t('workspace.loggedIn')"
            referrerpolicy="no-referrer"
            class="h-7 w-7 flex-shrink-0 rounded-full object-cover"
          />
          <span
            v-else
            class="flex h-7 w-7 flex-shrink-0 items-center justify-center rounded-full bg-secondary text-muted-foreground"
          >
            <User class="h-4 w-4" />
          </span>
          <span class="truncate text-sm text-muted-foreground">{{ nickName || t('workspace.loggedIn') }}</span>
        </div>
        <button
          :title="t('workspace.logout')"
          class="flex flex-shrink-0 items-center gap-1 rounded-lg px-2 py-1.5 text-sm text-muted-foreground transition-colors hover:bg-secondary hover:text-foreground"
          @click="$emit('logout')"
        >
          <LogOut class="h-4 w-4" />
        </button>
      </div>
    </div>
  </aside>
</template>

<script setup>
import { Presentation, Plus, Compass, LogOut, FileText, Loader2, User } from 'lucide-vue-next'
import { useI18n } from 'vue-i18n'
import LocaleSwitcher from '../LocaleSwitcher.vue'
import WorkspaceCreditsBar from './WorkspaceCreditsBar.vue'

defineProps({
  view: { type: String, default: 'new' },
  activeProjectId: { type: String, default: null },
  nickName: { type: String, default: '' },
  avatar: { type: String, default: '' },
  myProjects: { type: Array, default: () => [] },
  loadingProjects: { type: Boolean, default: false },
})
defineEmits(['new', 'explore', 'open-project', 'logout'])

const { t } = useI18n()

const btnClass = (active) => [
  'flex w-full items-center gap-2 rounded-lg px-3 py-2.5 text-sm font-medium transition-colors',
  active ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-secondary hover:text-foreground',
]
</script>
