// components/hero-section.tsx
import { Sparkles } from "lucide-react"

export function HeroSection() {
  return (
    <section className="relative overflow-hidden py-20 sm:py-32">
      {/* Background gradient */}
      <div className="pointer-events-none absolute inset-0 flex items-center justify-center">
        <div className="h-[500px] w-[500px] rounded-full bg-primary/10 blur-[120px]" />
      </div>

      <div className="relative mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="text-center">
          <div className="mb-6 inline-flex items-center gap-2 rounded-full border border-primary/30 bg-primary/10 px-4 py-1.5">
            <Sparkles className="h-4 w-4 text-primary" />
            <span className="text-sm font-medium text-primary">AI 驱动的演示文稿生成</span>
          </div>

          <h1 className="mx-auto max-w-4xl text-balance text-4xl font-bold tracking-tight text-foreground sm:text-6xl lg:text-7xl">
            将想法瞬间转化为
            <span className="text-primary">专业演示文稿</span>
          </h1>

          <p className="mx-auto mt-6 max-w-2xl text-pretty text-lg text-muted-foreground sm:text-xl">
            上传图书、资料进行智能分析，或通过一句话描述快速生成精美的PPT。让AI帮你完成繁琐的演示文稿制作工作。
          </p>

          <div className="mt-10 flex flex-col items-center justify-center gap-4 sm:flex-row">
            <a
              href="#generator"
              className="inline-flex items-center justify-center rounded-lg bg-primary px-8 py-3 text-base font-semibold text-primary-foreground shadow-lg shadow-primary/25 transition-all hover:bg-primary/90 hover:shadow-xl hover:shadow-primary/30"
            >
              立即体验
            </a>
            <a
              href="#features"
              className="inline-flex items-center justify-center rounded-lg border border-border bg-secondary/50 px-8 py-3 text-base font-semibold text-foreground transition-colors hover:bg-secondary"
            >
              了解更多
            </a>
          </div>
        </div>
      </div>
    </section>
  )
}

// vue-export/src/components/HeroSection.vue
<template>
  <section class="relative overflow-hidden pt-32 pb-16">
    <!-- Background gradient -->
    <div class="pointer-events-none absolute inset-0 overflow-hidden">
      <div class="absolute -top-40 -right-40 h-[500px] w-[500px] rounded-full bg-primary/10 blur-3xl" />
      <div class="absolute -bottom-40 -left-40 h-[400px] w-[400px] rounded-full bg-accent/10 blur-3xl" />
    </div>
    
    <div class="relative mx-auto max-w-4xl px-6 text-center">
      <div class="mb-6 inline-flex items-center gap-2 rounded-full border border-border bg-card/50 px-4 py-2 text-sm text-muted-foreground">
        <Sparkles class="h-4 w-4 text-primary" />
        <span>AI 驱动的智能演示文稿生成</span>
      </div>
      
      <h1 class="mb-6 text-balance text-4xl font-bold tracking-tight text-foreground sm:text-5xl lg:text-6xl">
        一句话生成
        <span class="bg-gradient-to-r from-primary to-accent bg-clip-text text-transparent">
          专业PPT
        </span>
      </h1>
      
      <p class="mx-auto mb-10 max-w-2xl text-pretty text-lg text-muted-foreground sm:text-xl">
        上传图书、论文、资料，AI 自动提取核心内容并生成结构化演示文稿。
        或者只需输入一句话，即刻获得精美 PPT。
      </p>
      
      <div class="flex flex-col items-center justify-center gap-4 sm:flex-row">
        <button 
          @click="scrollToGenerator"
          class="flex items-center gap-2 rounded-xl bg-primary px-8 py-4 text-base font-semibold text-primary-foreground shadow-lg shadow-primary/25 transition-all hover:bg-primary/90 hover:shadow-xl hover:shadow-primary/30"
        >
          <Zap class="h-5 w-5" />
          立即开始
        </button>
        <button class="flex items-center gap-2 rounded-xl border border-border bg-card/50 px-8 py-4 text-base font-medium text-foreground transition-colors hover:bg-card">
          <Play class="h-5 w-5" />
          观看演示
        </button>
      </div>
    </div>
  </section>
</template>

<script setup>
import { Sparkles, Zap, Play } from 'lucide-vue-next'

const scrollToGenerator = () => {
  document.getElementById('generator')?.scrollIntoView({ behavior: 'smooth' })
}
</script>
