// vue-export/src/App.vue
<template>
  <div class="min-h-screen bg-background">
    <AppHeader />
    <main>
      <HeroSection />
      <GeneratorSection />
      <FeatureCards />
    </main>
    <AppFooter />
  </div>
</template>

<script setup>
import AppHeader from './components/AppHeader.vue'
import HeroSection from './components/HeroSection.vue'
import GeneratorSection from './components/GeneratorSection.vue'
import FeatureCards from './components/FeatureCards.vue'
import AppFooter from './components/AppFooter.vue'
</script>

// app/page.tsx
"use client"

import { useState } from "react"
import { Header } from "@/components/header"
import { HeroSection } from "@/components/hero-section"
import { FeatureCards } from "@/components/feature-cards"
import { GeneratorSection } from "@/components/generator-section"
import { Footer } from "@/components/footer"

export default function Home() {
  const [activeTab, setActiveTab] = useState<"prompt" | "upload">("prompt")

  return (
    <div className="min-h-screen bg-background">
      <Header />
      <main>
        <HeroSection />
        <GeneratorSection activeTab={activeTab} setActiveTab={setActiveTab} />
        <FeatureCards />
      </main>
      <Footer />
    </div>
  )
}
