// vue-export/src/components/GeneratorSection.vue
<template>
  <section id="generator" class="py-20">
    <div class="mx-auto max-w-4xl px-6">
      <div class="overflow-hidden rounded-2xl border border-border bg-card shadow-2xl shadow-black/20">
        <!-- Tabs -->
        <div class="flex border-b border-border">
          <button
            v-for="tab in tabs"
            :key="tab.id"
            @click="activeTab = tab.id"
            :class="[
              'flex flex-1 items-center justify-center gap-2 px-6 py-4 text-sm font-medium transition-colors',
              activeTab === tab.id
                ? 'border-b-2 border-primary bg-card text-foreground'
                : 'text-muted-foreground hover:text-foreground'
            ]"
          >
            <component :is="tab.icon" class="h-4 w-4" />
            {{ tab.label }}
          </button>
        </div>

        <div class="p-6">
          <!-- Quick Start Mode -->
          <div v-if="activeTab === 'quick'" class="space-y-6">
            <div>
              <label class="mb-2 block text-sm font-medium text-foreground">
                描述你想要的 PPT 主题
              </label>
              <div class="relative">
                <textarea
                  v-model="prompt"
                  rows="4"
                  class="w-full resize-none rounded-xl border border-border bg-background px-4 py-3 text-foreground placeholder:text-muted-foreground focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                  placeholder="例如：关于人工智能在医疗领域应用的商业计划书，需要包含市场分析、技术方案、竞争优势和财务预测..."
                />
                <button
                  @click="generatePPT"
                  :disabled="isLoading || !prompt.trim()"
                  :class="[
                    'absolute bottom-3 right-3 flex items-center gap-2 rounded-lg px-4 py-2 text-sm font-medium transition-all',
                    isLoading || !prompt.trim()
                      ? 'cursor-not-allowed bg-muted text-muted-foreground'
                      : 'bg-primary text-primary-foreground hover:bg-primary/90'
                  ]"
                >
                  <Loader2 v-if="isLoading" class="h-4 w-4 animate-spin" />
                  <Sparkles v-else class="h-4 w-4" />
                  {{ isLoading ? '生成中...' : '生成 PPT' }}
                </button>
              </div>
            </div>

            <!-- Quick Start Buttons -->
            <div>
              <p class="mb-3 text-sm text-muted-foreground">快速开始：</p>
              <div class="flex flex-wrap gap-2">
                <button
                  v-for="example in quickExamples"
                  :key="example"
                  @click="prompt = example"
                  class="rounded-lg border border-border bg-background px-3 py-2 text-sm text-muted-foreground transition-colors hover:border-primary hover:text-foreground"
                >
                  {{ example }}
                </button>
              </div>
            </div>
          </div>

          <!-- Upload Mode -->
          <div v-else class="space-y-6">
            <div
              @dragover.prevent="isDragging = true"
              @dragleave="isDragging = false"
              @drop.prevent="handleDrop"
              :class="[
                'flex flex-col items-center justify-center rounded-xl border-2 border-dashed p-12 transition-colors',
                isDragging
                  ? 'border-primary bg-primary/5'
                  : 'border-border hover:border-muted-foreground'
              ]"
            >
              <div class="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-primary/10">
                <Upload class="h-8 w-8 text-primary" />
              </div>
              <p class="mb-2 text-lg font-medium text-foreground">
                拖放文件到这里
              </p>
              <p class="mb-4 text-sm text-muted-foreground">
                支持 PDF、Word、TXT、Markdown 格式
              </p>
              <label class="cursor-pointer rounded-lg bg-primary px-6 py-2.5 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90">
                选择文件
                <input
                  type="file"
                  class="hidden"
                  accept=".pdf,.doc,.docx,.txt,.md"
                  @change="handleFileSelect"
                />
              </label>
            </div>

            <!-- Selected File -->
            <div v-if="selectedFile" class="flex items-center gap-3 rounded-lg border border-border bg-background p-4">
              <div class="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10">
                <FileText class="h-5 w-5 text-primary" />
              </div>
              <div class="flex-1 min-w-0">
                <p class="truncate text-sm font-medium text-foreground">
                  {{ selectedFile.name }}
                </p>
                <p class="text-xs text-muted-foreground">
                  {{ formatFileSize(selectedFile.size) }}
                </p>
              </div>
              <button
                @click="selectedFile = null"
                class="rounded-lg p-2 text-muted-foreground transition-colors hover:bg-muted hover:text-foreground"
              >
                <X class="h-4 w-4" />
              </button>
            </div>

            <button
              @click="analyzeDocument"
              :disabled="isLoading || !selectedFile"
              :class="[
                'flex w-full items-center justify-center gap-2 rounded-xl py-4 text-base font-medium transition-all',
                isLoading || !selectedFile
                  ? 'cursor-not-allowed bg-muted text-muted-foreground'
                  : 'bg-primary text-primary-foreground hover:bg-primary/90'
              ]"
            >
              <Loader2 v-if="isLoading" class="h-5 w-5 animate-spin" />
              <FileSearch v-else class="h-5 w-5" />
              {{ isLoading ? '分析中...' : '分析并生成 PPT' }}
            </button>
          </div>

          <!-- Generated Slides Preview -->
          <div v-if="slides.length > 0" class="mt-8 space-y-4">
            <div class="flex items-center justify-between">
              <h3 class="text-lg font-semibold text-foreground">生成的大纲</h3>
              <button
                @click="downloadPPT"
                :disabled="isDownloading"
                class="flex items-center gap-2 rounded-lg bg-accent px-4 py-2 text-sm font-medium text-accent-foreground transition-colors hover:bg-accent/90"
              >
                <Loader2 v-if="isDownloading" class="h-4 w-4 animate-spin" />
                <Download v-else class="h-4 w-4" />
                {{ isDownloading ? '下载中...' : '下载 PPTX' }}
              </button>
            </div>
            
            <div class="space-y-3">
              <div
                v-for="(slide, index) in slides"
                :key="index"
                class="rounded-lg border border-border bg-background p-4"
              >
                <div class="mb-2 flex items-center gap-2">
                  <span class="flex h-6 w-6 items-center justify-center rounded bg-primary/10 text-xs font-medium text-primary">
                    {{ index + 1 }}
                  </span>
                  <h4 class="font-medium text-foreground">{{ slide.title }}</h4>
                </div>
                <ul class="space-y-1 pl-8">
                  <li
                    v-for="(point, pointIndex) in slide.points"
                    :key="pointIndex"
                    class="text-sm text-muted-foreground"
                  >
                    {{ point }}
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</template>

<script setup>
import { ref, markRaw } from 'vue'
import { 
  Sparkles, 
  Upload, 
  FileText, 
  FileSearch, 
  Download, 
  Loader2, 
  X,
  MessageSquare,
  FileUp
} from 'lucide-vue-next'
const emit = defineEmits(['start'])

const activeTab = ref('quick')
const prompt = ref('')
const isLoading = ref(false)
const isDownloading = ref(false)
const isDragging = ref(false)
const selectedFile = ref(null)
const slides = ref([])

const tabs = [
  { id: 'quick', label: '一句话生成', icon: markRaw(MessageSquare) },
  { id: 'upload', label: '上传资料分析', icon: markRaw(FileUp) }
]

const quickExamples = [
  '商业计划书',
  '项目汇报',
  '产品介绍',
  '年终总结',
  '技术分享'
]

const formatFileSize = (bytes) => {
  if (bytes < 1024) return bytes + ' B'
  if (bytes < 1024 * 1024) return (bytes / 1024).toFixed(1) + ' KB'
  return (bytes / (1024 * 1024)).toFixed(1) + ' MB'
}

const handleDrop = (e) => {
  isDragging.value = false
  const files = e.dataTransfer.files
  if (files.length > 0) {
    selectedFile.value = files[0]
  }
}

const handleFileSelect = (e) => {
  const files = e.target.files
  if (files.length > 0) {
    selectedFile.value = files[0]
  }
}

// 落地页仅作引导：点击生成/分析 → 交由父级处理（登录或进入工作区）
const generatePPT = () => {
  emit('start', { mode: 'prompt', prompt: prompt.value })
}

const analyzeDocument = () => {
  emit('start', { mode: 'upload' })
}

const downloadPPT = () => {
  emit('start', { mode: 'prompt', prompt: prompt.value })
}
</script>

// components/generator-section.tsx
"use client"

import { useState, useRef } from "react"
import { MessageSquare, Upload, Sparkles, FileText, Loader2, Download, ChevronRight, X } from "lucide-react"
import { useChat } from "@ai-sdk/react"

interface GeneratorSectionProps {
  activeTab: "prompt" | "upload"
  setActiveTab: (tab: "prompt" | "upload") => void
}

export function GeneratorSection({ activeTab, setActiveTab }: GeneratorSectionProps) {
  const [uploadedFile, setUploadedFile] = useState<File | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)
  const [generatedSlides, setGeneratedSlides] = useState<Slide[] | null>(null)
  const fileInputRef = useRef<HTMLInputElement>(null)

  const { messages, input, handleInputChange, handleSubmit, isLoading } = useChat({
    api: "/api/generate-ppt",
    onFinish: (message) => {
      try {
        const content = message.content
        const jsonMatch = content.match(/```json\n?([\s\S]*?)\n?```/)
        if (jsonMatch) {
          const slides = JSON.parse(jsonMatch[1])
          setGeneratedSlides(slides)
        } else {
          const slides = JSON.parse(content)
          setGeneratedSlides(slides)
        }
      } catch {
        console.log("[v0] Could not parse slides from response")
      }
    },
  })

  const handleFileUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0]
    if (file) {
      setUploadedFile(file)
    }
  }

  const handleAnalyzeDocument = async () => {
    if (!uploadedFile) return
    setIsGenerating(true)

    const formData = new FormData()
    formData.append("file", uploadedFile)

    try {
      const response = await fetch("/api/analyze-document", {
        method: "POST",
        body: formData,
      })
      const data = await response.json()
      if (data.slides) {
        setGeneratedSlides(data.slides)
      }
    } catch (error) {
      console.error("[v0] Error analyzing document:", error)
    } finally {
      setIsGenerating(false)
    }
  }

  const handleDownloadPPT = async () => {
    if (!generatedSlides) return

    try {
      const response = await fetch("/api/download-ppt", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ slides: generatedSlides }),
      })

      const blob = await response.blob()
      const url = window.URL.createObjectURL(blob)
      const a = document.createElement("a")
      a.href = url
      a.download = "presentation.pptx"
      document.body.appendChild(a)
      a.click()
      document.body.removeChild(a)
      window.URL.revokeObjectURL(url)
    } catch (error) {
      console.error("[v0] Error downloading PPT:", error)
    }
  }

  return (
    <section id="generator" className="py-16 sm:py-24">
      <div className="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
        <div className="mx-auto max-w-3xl">
          {/* Tab Switcher */}
          <div className="mb-8 flex items-center justify-center">
            <div className="inline-flex rounded-xl border border-border bg-secondary/30 p-1.5">
              <button
                onClick={() => setActiveTab("prompt")}
                className={`flex items-center gap-2 rounded-lg px-6 py-2.5 text-sm font-medium transition-all ${
                  activeTab === "prompt"
                    ? "bg-primary text-primary-foreground shadow-lg"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                <MessageSquare className="h-4 w-4" />
                一句话生成
              </button>
              <button
                onClick={() => setActiveTab("upload")}
                className={`flex items-center gap-2 rounded-lg px-6 py-2.5 text-sm font-medium transition-all ${
                  activeTab === "upload"
                    ? "bg-primary text-primary-foreground shadow-lg"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                <Upload className="h-4 w-4" />
                上传资料分析
              </button>
            </div>
          </div>

          {/* Generator Card */}
          <div className="overflow-hidden rounded-2xl border border-border bg-card shadow-2xl shadow-primary/5">
            {activeTab === "prompt" ? (
              <div className="p-6 sm:p-8">
                <div className="mb-6">
                  <h3 className="text-lg font-semibold text-foreground">描述你想要的演示文稿</h3>
                  <p className="mt-1 text-sm text-muted-foreground">
                    输入主题、风格和内容要求，AI将为你生成专业的PPT
                  </p>
                </div>

                <form onSubmit={handleSubmit} className="space-y-4">
                  <div className="relative">
                    <textarea
                      value={input}
                      onChange={handleInputChange}
                      placeholder="例如：帮我生成一个关于人工智能发展历史的10页PPT，包含时间线、关键人物和未来展望..."
                      className="min-h-[140px] w-full resize-none rounded-xl border border-border bg-secondary/50 px-4 py-4 text-foreground placeholder:text-muted-foreground/60 focus:border-primary focus:outline-none focus:ring-2 focus:ring-primary/20"
                    />
                    <div className="absolute bottom-3 right-3">
                      <Sparkles className="h-5 w-5 text-muted-foreground/40" />
                    </div>
                  </div>

                  <button
                    type="submit"
                    disabled={isLoading || !input?.trim()}
                    className="flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3.5 font-semibold text-primary-foreground transition-all hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {isLoading ? (
                      <>
                        <Loader2 className="h-5 w-5 animate-spin" />
                        正在生成...
                      </>
                    ) : (
                      <>
                        <Sparkles className="h-5 w-5" />
                        生成演示文稿
                      </>
                    )}
                  </button>
                </form>

                {/* Quick Prompts */}
                <div className="mt-6 border-t border-border pt-6">
                  <p className="mb-3 text-xs font-medium uppercase tracking-wider text-muted-foreground">
                    快速开始
                  </p>
                  <div className="flex flex-wrap gap-2">
                    {[
                      "商业计划书",
                      "项目汇报",
                      "产品介绍",
                      "年度总结",
                      "培训课件",
                    ].map((prompt) => (
                      <button
                        key={prompt}
                        onClick={() => {
                          const event = {
                            target: { value: `帮我生成一个${prompt}的PPT，要求专业、简洁、有吸引力` },
                          } as React.ChangeEvent<HTMLInputElement>
                          handleInputChange(event)
                        }}
                        className="rounded-lg border border-border bg-secondary/50 px-3 py-1.5 text-sm text-muted-foreground transition-colors hover:border-primary/50 hover:text-foreground"
                      >
                        {prompt}
                      </button>
                    ))}
                  </div>
                </div>
              </div>
            ) : (
              <div className="p-6 sm:p-8">
                <div className="mb-6">
                  <h3 className="text-lg font-semibold text-foreground">上传文档进行分析</h3>
                  <p className="mt-1 text-sm text-muted-foreground">
                    支持 PDF、Word、TXT 等格式，AI将提取关键内容生成PPT
                  </p>
                </div>

                <div
                  onClick={() => fileInputRef.current?.click()}
                  className="cursor-pointer rounded-xl border-2 border-dashed border-border bg-secondary/30 p-8 text-center transition-colors hover:border-primary/50 hover:bg-secondary/50"
                >
                  <input
                    ref={fileInputRef}
                    type="file"
                    onChange={handleFileUpload}
                    accept=".pdf,.doc,.docx,.txt,.md"
                    className="hidden"
                  />
                  {uploadedFile ? (
                    <div className="flex items-center justify-center gap-3">
                      <FileText className="h-10 w-10 text-primary" />
                      <div className="text-left">
                        <p className="font-medium text-foreground">{uploadedFile.name}</p>
                        <p className="text-sm text-muted-foreground">
                          {(uploadedFile.size / 1024 / 1024).toFixed(2)} MB
                        </p>
                      </div>
                      <button
                        onClick={(e) => {
                          e.stopPropagation()
                          setUploadedFile(null)
                        }}
                        className="ml-4 rounded-lg p-1 hover:bg-secondary"
                      >
                        <X className="h-5 w-5 text-muted-foreground" />
                      </button>
                    </div>
                  ) : (
                    <>
                      <Upload className="mx-auto h-12 w-12 text-muted-foreground/50" />
                      <p className="mt-4 font-medium text-foreground">点击或拖拽文件到此处</p>
                      <p className="mt-1 text-sm text-muted-foreground">
                        支持 PDF, Word, TXT, Markdown 格式
                      </p>
                    </>
                  )}
                </div>

                <button
                  onClick={handleAnalyzeDocument}
                  disabled={!uploadedFile || isGenerating}
                  className="mt-6 flex w-full items-center justify-center gap-2 rounded-xl bg-primary py-3.5 font-semibold text-primary-foreground transition-all hover:bg-primary/90 disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {isGenerating ? (
                    <>
                      <Loader2 className="h-5 w-5 animate-spin" />
                      正在分析文档...
                    </>
                  ) : (
                    <>
                      <Sparkles className="h-5 w-5" />
                      分析并生成PPT
                    </>
                  )}
                </button>
              </div>
            )}

            {/* Generated Slides Preview */}
            {generatedSlides && (
              <div className="border-t border-border bg-secondary/20 p-6 sm:p-8">
                <div className="mb-4 flex items-center justify-between">
                  <h4 className="font-semibold text-foreground">生成的幻灯片预览</h4>
                  <button
                    onClick={handleDownloadPPT}
                    className="flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
                  >
                    <Download className="h-4 w-4" />
                    下载 PPTX
                  </button>
                </div>

                <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                  {generatedSlides.map((slide, index) => (
                    <div
                      key={index}
                      className="group relative aspect-video overflow-hidden rounded-lg border border-border bg-card p-4 transition-all hover:border-primary/50"
                    >
                      <div className="absolute right-2 top-2 rounded bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">
                        {index + 1}
                      </div>
                      <h5 className="line-clamp-2 text-sm font-semibold text-foreground">
                        {slide.title}
                      </h5>
                      <ul className="mt-2 space-y-1">
                        {slide.content.slice(0, 3).map((item, i) => (
                          <li key={i} className="flex items-start gap-1.5 text-xs text-muted-foreground">
                            <ChevronRight className="mt-0.5 h-3 w-3 shrink-0 text-primary" />
                            <span className="line-clamp-1">{item}</span>
                          </li>
                        ))}
                        {slide.content.length > 3 && (
                          <li className="text-xs text-muted-foreground/60">
                            +{slide.content.length - 3} 更多...
                          </li>
                        )}
                      </ul>
                    </div>
                  ))}
                </div>
              </div>
            )}
          </div>

          {/* AI Response Display */}
          {messages.length > 0 && !generatedSlides && (
            <div className="mt-6 rounded-xl border border-border bg-card p-6">
              <h4 className="mb-4 font-semibold text-foreground">AI 正在思考...</h4>
              <div className="prose prose-invert max-w-none text-sm text-muted-foreground">
                {messages[messages.length - 1]?.content}
              </div>
            </div>
          )}
        </div>
      </div>
    </section>
  )
}

interface Slide {
  title: string
  content: string[]
}
